volumes:
  fotoflowDb:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: fotoflowDb

    ports:
      - "5432:5432"

    volumes:
      - fotoflowDb:/var/lib/postgresql/data
