--VIEW CLIENTES
CREATE VIEW V_CLIENTES AS
	SELECT U.ID_USUARIO, U.NOME, U.EMAIL, U.SENHA, U.TELEFONE, U.ENDERECO
	FROM USUARIOS U
	INNER JOIN CLIENTES C ON U.ID_USUARIO = C.ID_CLIENTE
	
SELECT * FROM v_CLIENTES


--VIEW FOTOGRAFOS
CREATE VIEW V_FOTOGRAFOS AS
	SELECT U.ID_USUARIO, U.NOME, U.EMAIL, U.SENHA, U.TELEFONE, U.ENDERECO, F.ESPECIALIDADE, F.CERTIFICACOES
	FROM USUARIOS U
	INNER JOIN FOTOGRAFOS F ON U.ID_USUARIO = F.ID_FOTOGRAFO
	
SELECT * FROM V_FOTOGRAFOS

--VIEW ALBUMS
CREATE VIEW V_ALBUM AS
	SELECT A.*, U.NOME AS FOTOGRAFO
	FROM ALBUM A
	JOIN USUARIOS U ON A.FOTOGRAFO_ID = U.ID_USUARIO;

SELECT * FROM v_album

--VIEW FOTOS
CREATE VIEW V_FOTOS AS
	SELECT F.*
	FROM FOTOS F
	JOIN album a ON F.ALBUM_ID = A.ID_ALBUM
	
SELECT * FROM V_FOTOS


